"""Prompt module."""

from app.prompt.instructions import (
    AGENT_DESCRIPTION,
    AIOK_SYSTEM_INSTRUCTION,
    CLASSIFIER_INSTRUCTION,
    EMAIL_REPLY_INSTRUCTION,
    EMAIL_SUMMARIZE_INSTRUCTION,
    ISSUE_LINKER_INSTRUCTION,
    MEETING_ACTION_ITEMS_INSTRUCTION,
    MEETING_SUMMARIZE_INSTRUCTION,
    PR_ANALYZER_INSTRUCTION,
    PR_COLLECTOR_INSTRUCTION,
    PR_FETCHER_INSTRUCTION,
    PR_REVIEWER_INSTRUCTION,
    RELEASE_WRITER_INSTRUCTION,
    TRANSLATION_INSTRUCTION,
)

__all__ = [
    "AIOK_SYSTEM_INSTRUCTION",
    "AGENT_DESCRIPTION",
    "EMAIL_SUMMARIZE_INSTRUCTION",
    "EMAIL_REPLY_INSTRUCTION",
    "MEETING_SUMMARIZE_INSTRUCTION",
    "MEETING_ACTION_ITEMS_INSTRUCTION",
    "TRANSLATION_INSTRUCTION",
    "PR_FETCHER_INSTRUCTION",
    "PR_ANALYZER_INSTRUCTION",
    "PR_REVIEWER_INSTRUCTION",
    "PR_COLLECTOR_INSTRUCTION",
    "ISSUE_LINKER_INSTRUCTION",
    "CLASSIFIER_INSTRUCTION",
    "RELEASE_WRITER_INSTRUCTION",
]
